### PR TITLE
Releasing Version 2.2.0

### PR DESCRIPTION
**Pull request by jrg94**
For whatever reason, I held onto this release since May. Thanks for y'alls patience. 

All this pull request does is cleanup some of the existing code and update the version number in the project file.

### CODE REVIEW

**Comment by jrg94** [comment]
Going to toy with Python 3.12 real quick. See if we can support it.

**Review by rzuckerm — APPROVED** [review]
LGTM

**Comment by jrg94** [comment]
Okay, 3.12 does not work. Good to know!

**Comment by rzuckerm** [comment]
Hmm, looks like Python 3.12 isn't working.

**Pull request merged**
